/**
 * DocuVoz speech sidecar — HTTP app factory.
 *
 * A minimal, long-lived surface that reuses the existing speech runtime:
 *   - `handleSpeech` (framework-agnostic, src/server/api/speech-handler.ts)
 *   - `createEngines` / provider config (src/server/config.ts)
 *   - Edge / NaN / Mock providers + PacedProvider + DeadlineWrapper
 *   - FileAudioCache, rate limiter, structured logging
 *
 * It does NOT embed Next.js. The entrypoint (`sidecar/server.ts`) binds only
 * to 127.0.0.1 on an ephemeral port (port 0) and prints exactly one
 * machine-readable readiness line:
 *
 *   READY {"port":12345}
 *
 * Auth: every request must carry `Authorization: Bearer <token>`. The token is
 * generated per-process by the Rust host and passed via the environment
 * (never a CLI argument, never printed, never logged).
 *
 * Protocol:
 *   GET  /health              -> JSON HealthDescriptor (authorized)
 *   POST /speech?requestId=..  -> binary frame (metadata + audio) or error frame
 *   POST /cancel/<requestId>   -> abort that request (AbortController.abort())
 *
 * Binary frame:
 *   uint32 metadataLength (LE) | UTF-8 metadata JSON | raw audio bytes
 */
import { createHash } from "node:crypto";
import {
  createServer,
  type IncomingMessage,
  type Server,
  type ServerResponse,
} from "node:http";
import { handleSpeech, type HandlerDeps } from "@/server/api/speech-handler";
import { SPOKEN_ENGINE_VERSION } from "@/domain/spoken/version";

const MAX_METADATA_BYTES = 64 * 1024;

export interface SidecarAppOptions {
  /** Bearer token required on every request (generated by the Rust host). */
  token: string;
  /** Existing speech runtime wiring (config, provider, engines, cache...). */
  deps: HandlerDeps;
}

export interface SidecarApp {
  server: Server;
  /** requestId -> AbortController for in-flight synthesis requests. */
  pending: Map<string, AbortController>;
  /** Start listening on 127.0.0.1; resolves with the bound port. */
  listen(port?: number): Promise<number>;
  /** Abort in-flight requests, stop accepting connections, resolve when closed. */
  shutdown(): Promise<void>;
}

export function createSidecarApp({ token, deps }: SidecarAppOptions): SidecarApp {
  const pending = new Map<string, AbortController>();

  /** Length-safe constant-time comparison (hash both sides first). */
  function authorized(req: IncomingMessage): boolean {
    const provided = req.headers.authorization ?? "";
    const expected = `Bearer ${token}`;
    const a = createHash("sha256").update(provided).digest();
    const b = createHash("sha256").update(expected).digest();
    return a.equals(b);
  }

  function healthDescriptor() {
    const config = deps.config;
    const engines = deps.engines ?? [];
    const def = engines[0];
    if (!def) throw new Error("no engines configured");
    return {
      ok: true,
      provider: def.provider.name,
      model: def.model,
      voice: def.defaultVoice,
      speed: config.SPEECH_DEFAULT_SPEED,
      format: def.format,
      maxTextChars: config.SPEECH_MAX_TEXT_CHARS,
      spokenEngineVersion: SPOKEN_ENGINE_VERSION,
      engines: engines.map((e) => ({
        id: e.id,
        label: e.label,
        provider: e.provider.name,
        model: e.model,
        format: e.format,
      })),
    };
  }

  function writeJson(res: ServerResponse, status: number, body: unknown): void {
    res.writeHead(status, { "content-type": "application/json" });
    res.end(JSON.stringify(body));
  }

  function encodeFrame(metadata: Record<string, unknown>, audio: Uint8Array): Buffer {
    const metaBytes = Buffer.from(JSON.stringify(metadata), "utf-8");
    if (metaBytes.length > MAX_METADATA_BYTES) {
      // Boundaries are the only unbounded part; drop them rather than fail.
      const rest = { ...metadata };
      delete rest.boundaries;
      return encodeFrame(rest, audio);
    }
    const header = Buffer.alloc(4);
    header.writeUInt32LE(metaBytes.length, 0);
    return Buffer.concat([header, metaBytes, audio]);
  }

  /** Read a request body incrementally, rejecting when bytes exceed `maxBytes`. */
  function readBodyBounded(req: IncomingMessage, maxBytes: number): Promise<Uint8Array> {
    return new Promise((resolve, reject) => {
      const chunks: Buffer[] = [];
      let total = 0;
      let done = false;
      req.on("data", (chunk: Buffer) => {
        if (done) return; // over the limit: keep draining, never accumulate
        total += chunk.length;
        if (total > maxBytes) {
          done = true;
          reject(new Error("body_too_large"));
          return;
        }
        chunks.push(chunk);
      });
      req.on("end", () => {
        if (done) return;
        done = true;
        resolve(Buffer.concat(chunks));
      });
      req.on("error", (err) => {
        if (!done) {
          done = true;
          reject(err);
        }
      });
    });
  }

  async function handleSpeechRequest(
    req: IncomingMessage,
    res: ServerResponse,
  ): Promise<void> {
    if (!authorized(req)) {
      res.writeHead(401, { "content-type": "application/json" });
      res.end(JSON.stringify({ error: "unauthorized" }));
      return;
    }
    const contentType = req.headers["content-type"] ?? "";
    if (!contentType.includes("application/json")) {
      res.writeHead(415, { "content-type": "application/json" });
      res.end(JSON.stringify({ error: "unsupported_media_type" }));
      return;
    }

    const url = new URL(req.url ?? "/", "http://127.0.0.1");
    const requestId = (url.searchParams.get("requestId") ?? "").slice(0, 128);
    const controller = new AbortController();
    if (requestId) pending.set(requestId, controller);

    let rawBody: Uint8Array;
    try {
      rawBody = await readBodyBounded(req, deps.config.API_MAX_BODY_BYTES);
    } catch {
      if (requestId) pending.delete(requestId);
      // Respond BEFORE tearing down the socket: undici (and any HTTP/1.1
      // client) must receive the 413 rather than see a connection reset.
      // The oversized body drains silently (nothing is accumulated) and the
      // socket is destroyed once the response is flushed.
      res.writeHead(413, {
        "content-type": "application/json",
        connection: "close",
      });
      res.end(JSON.stringify({ error: "too_large" }));
      res.on("finish", () => req.socket.destroy());
      return;
    }

    let raw: unknown;
    try {
      raw = JSON.parse(Buffer.from(rawBody).toString("utf-8"));
    } catch {
      if (requestId) pending.delete(requestId);
      res.writeHead(400, { "content-type": "application/json" });
      res.end(JSON.stringify({ error: "invalid_request" }));
      return;
    }

    const result = await handleSpeech(raw, "local", deps, controller.signal);
    if (requestId) pending.delete(requestId);

    if (result.audio) {
      const metadata: Record<string, unknown> = {
        mimeType: result.headers["content-type"] ?? "application/octet-stream",
        cacheKey: result.headers["cache-key"] ?? "",
        cacheStatus: result.headers["cache-status"] ?? "none",
        providerName: result.headers["x-provider"],
      };
      const boundariesHeader = result.headers["x-word-boundaries"];
      if (boundariesHeader) {
        try {
          metadata.boundaries = JSON.parse(
            Buffer.from(boundariesHeader, "base64").toString("utf-8"),
          );
        } catch {
          /* ignore malformed boundaries — audio is unaffected */
        }
      }
      const durationHeader = result.headers["request-duration-ms"];
      if (durationHeader) metadata.providerDurationMs = Number(durationHeader);
      const frame = encodeFrame(metadata, result.audio);
      res.writeHead(200, {
        "content-type": "application/octet-stream",
        "content-length": String(frame.length),
      });
      res.end(frame);
      return;
    }

    // Non-audio response (error): encode the stable code into an error frame so
    // the frontend transport can throw it without an HTTP status.
    const body = (result.body as { error?: string } | undefined)?.error ?? "speech_error";
    const frame = encodeFrame({ error: body }, new Uint8Array(0));
    res.writeHead(200, { "content-type": "application/octet-stream" });
    res.end(frame);
  }

  function handleCancel(req: IncomingMessage, res: ServerResponse): void {
    if (!authorized(req)) {
      res.writeHead(401, { "content-type": "application/json" });
      res.end(JSON.stringify({ error: "unauthorized" }));
      return;
    }
    const match = /^\/cancel\/([^/]+)$/.exec(req.url ?? "");
    const requestId = match?.[1];
    const controller = requestId ? pending.get(decodeURIComponent(requestId)) : undefined;
    if (controller) {
      controller.abort();
      pending.delete(requestId!);
    }
    res.writeHead(204);
    res.end();
  }

  const server = createServer((req, res) => {
    void (async () => {
      try {
        const url = new URL(req.url ?? "/", "http://127.0.0.1");
        if (url.pathname === "/health" && req.method === "GET") {
          if (!authorized(req)) {
            res.writeHead(401, { "content-type": "application/json" });
            res.end(JSON.stringify({ error: "unauthorized" }));
            return;
          }
          writeJson(res, 200, healthDescriptor());
          return;
        }
        if (url.pathname === "/speech" && req.method === "POST") {
          await handleSpeechRequest(req, res);
          return;
        }
        if (url.pathname.startsWith("/cancel/") && req.method === "POST") {
          handleCancel(req, res);
          return;
        }
        res.writeHead(404, { "content-type": "application/json" });
        res.end(JSON.stringify({ error: "not_found" }));
      } catch {
        if (!res.headersSent) {
          res.writeHead(500, { "content-type": "application/json" });
          res.end(JSON.stringify({ error: "internal" }));
        } else {
          res.destroy();
        }
      }
    })();
  });

  return {
    server,
    pending,
    listen(port = 0) {
      return new Promise<number>((resolve, reject) => {
        server.once("error", reject);
        server.listen(port, "127.0.0.1", () => {
          const address = server.address();
          const bound = typeof address === "object" && address ? address.port : port;
          resolve(bound);
        });
      });
    },
    shutdown() {
      for (const controller of pending.values()) controller.abort();
      pending.clear();
      return new Promise<void>((resolve) => {
        server.close(() => resolve());
      });
    },
  };
}
